name: Deploy App

on:
  push:
    tags:
      - 'v.*.*.*'
    branches:
      - feat/evaluacion_sumativa_1
  workflow_dispatch:


jobs:
  call-docker-workflow:
    uses: AUY1104-SDLC-II/devops-library/.github/workflows/build-push.yml@feat/evaluacion_sumativa_1
    with:
      image-name: demo-api
      image-tag: ${{ github.ref_name}}
    secrets:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#test